version: '3.4'

services:
    ctsData:
        container_name: ctsData
        ports:
            - "1473:1433"
        environment:
            SA_PASSWORD: "Staycool@99"
            ACCEPT_EULA: "Y"

    covidtracing.api:
        container_name: covidtrackingapi
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "ConnectionStrings:CovidTracingAPIDBContext=Server=ctsData;Database=CTSData;User Id=SA;Password=Staycool@99;"
        ports:
            - "8001:80"
        depends_on:
            - ctsData
        volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https/